### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by wengqi123** [parklab/PaSDqc#5]
$ make
python setup.py sdist
running sdist
running egg_info
creating PaSDqc.egg-info
writing requirements to PaSDqc.egg-info/requires.txt
writing PaSDqc.egg-info/PKG-INFO
writing top-level names to PaSDqc.egg-info/top_level.txt
writing dependency_links to PaSDqc.egg-info/dependency_links.txt
writing manifest file 'PaSDqc.egg-info/SOURCES.txt'
reading manifest file 'PaSDqc.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'PaSDqc.egg-info/SOURCES.txt'
running check
creating PaSDqc-1.1.0
creating PaSDqc-1.1.0/PaSDqc
creating PaSDqc-1.1.0/PaSDqc.egg-info
creating PaSDqc-1.1.0/PaSDqc/db
creating PaSDqc-1.1.0/scripts
copying files to PaSDqc-1.1.0...
copying MANIFEST.in -> PaSDqc-1.1.0
copying README.md -> PaSDqc-1.1.0
copying setup.py -> PaSDqc-1.1.0
copying PaSDqc/PSDTools.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/__init__.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/amplicon.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/extra_tools.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/mappable_positions.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/plotly_tools.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/report_writer.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc/simulate.py -> PaSDqc-1.1.0/PaSDqc
copying PaSDqc.egg-info/PKG-INFO -> PaSDqc-1.1.0/PaSDqc.egg-info
copying PaSDqc.egg-info/SOURCES.txt -> PaSDqc-1.1.0/PaSDqc.egg-info
copying PaSDqc.egg-info/dependency_links.txt -> PaSDqc-1.1.0/PaSDqc.egg-info
copying PaSDqc.egg-info/requires.txt -> PaSDqc-1.1.0/PaSDqc.egg-info
copying PaSDqc.egg-info/top_level.txt -> PaSDqc-1.1.0/PaSDqc.egg-info
copying PaSDqc/db/bulk_1x.smooth3.spec -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/categorical_spectra_0.1x.txt -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/categorical_spectra_1x.txt -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.centromeres.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr1.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr10.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr11.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr12.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr13.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr14.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr15.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr16.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr17.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr18.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr19.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr2.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr20.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr21.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr22.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr3.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr4.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr5.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr6.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr7.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr8.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chr9.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chrM.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chrX.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chrY.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/grch37.chrom.sizes -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.centromeres.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr1.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr10.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr11.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr12.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr13.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr14.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr15.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr16.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr17.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr18.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr19.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr2.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr20.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr21.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr22.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr3.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr4.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr5.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr6.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr7.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr8.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chr9.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chrM.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chrX.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying PaSDqc/db/hg19.chrY.map.bed -> PaSDqc-1.1.0/PaSDqc/db
copying scripts/PaSDqc -> PaSDqc-1.1.0/scripts
Writing PaSDqc-1.1.0/setup.cfg
creating dist
Creating tar archive
removing 'PaSDqc-1.1.0' (and everything under it)
pip install dist/*tar.gz
Processing ./dist/PaSDqc-1.1.0.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): PaSDqc==1.1.0 from file:///haplox/users/wenger/pipe/single_cell_wgs/bin/PaSDqc/dist/PaSDqc-1.1.0.tar.gz in /haplox/users/wenger/pipe/single_cell_wgs/bin/PaSDqc
Requirement already satisfied: seaborn in /home/wenger/.local/lib/python3.5/site-packages (from PaSDqc==1.1.0)
Collecting astropy (from PaSDqc==1.1.0)
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b69220dd860>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/astropy/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b69220ddc88>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/astropy/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b69220ddf28>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/astropy/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b69220ddbe0>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/astropy/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b69220ddba8>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/astropy/
  Could not find a version that satisfies the requirement astropy (from PaSDqc==1.1.0) (from versions: )
No matching distribution found for astropy (from PaSDqc==1.1.0)
make: *** [dist] Error 1

**Comment by wengqi123** [comment]
>>> import PaSDqc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PaSDqc/__init__.py", line 3, in <module>
    from . import amplicon
  File "PaSDqc/amplicon.py", line 13, in <module>
    from . import extra_tools
  File "PaSDqc/extra_tools.py", line 22, in <module>
    from . import PSDTools
  File "PaSDqc/PSDTools.py", line 16, in <module>
    from . import extra_tools

what the package name of above?
