### ISSUE TITLE
not able to run fully

### ISSUE THREAD

**Issue by proukakis** [parklab/PaSDqc#9]
hello
I am using a Mac El Capitan, and cant run it to the end

I first tried samples aligned to hg19 with "chr" included with the chromosome number, and it seems not to recognise this
eg
Processing: 1
Executing: samtools view -q 30 -L /usr/local/lib/python3.6/site-packages/PaSDqc/db/grch37.chr1.map.bed /Volumes/Toshiba4Tb/single_cell_data/67_10.picoplex.qs.oct18/67_10.SN.qiascout.picoplex.merged.bam 1 | cut -f 3,4 | uniq > /Volumes/Toshiba4Tb/single_cell_data/67_10.picoplex.qs.oct18/cov/67_10.SN.qiascout.picoplex.merged.chr1.map.pos
[main_samview] region "1" specifies an unknown reference name. Continue anyway.

I realigned data to hg19 without "chr", and seems to work, but only up to a point.

I then downloaded one of your SRA low coverage files, and get the exact same problem:

PaSDqc QC -i /Volumes/Toshiba4Tb/walsh.bam -d /Volumes/Toshiba4Tb/ -c db/categorical_spectra_0.1x.txt

......
Executing: samtools view -uh -q 30 /Volumes/Toshiba4Tb/walsh.bam 22 | samtools depth -b PaSDqc/cov/walsh.chr22.map.pos - > PaSDqc/cov/walsh.chr22.map.pos.cov; rm PaSDqc/cov/walsh.chr22.map.pos
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
PaSDqc/psd/walsh.chroms.spec
/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py:34: FutureWarning:

read_table is deprecated, use read_csv instead, passing sep='\t'.

PaSDqc/psd/SRS379201.walsh.chroms.spec
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/bin/PaSDqc", line 102, in _build_and_save
    psd = PaSDqc.PSDTools.SamplePSD.build_from_dir(str(dir_in), sample=sample, clean=clean, build=build)
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 268, in build_from_dir
    df = cls._build_dataframe(file_list, build)
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 313, in _build_dataframe
    psd_list = [ChromPSD(str(f)) for f in f_list]
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 313, in <listcomp>
    psd_list = [ChromPSD(str(f)) for f in f_list]
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 35, in __init__
    self.chrom = str(self.df.chrom.iloc[0])
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/usr/local/bin/PaSDqc", line 210, in QC
    PSD(args)
  File "/usr/local/bin/PaSDqc", line 95, in PSD
    [p.get() for p in res]
  File "/usr/local/bin/PaSDqc", line 95, in <listcomp>
    [p.get() for p in res]
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: single positional indexer is out-of-bounds

So I guess there is something wrong in my Python setup? If you have any suggestions, I will be grateful

thanks
christos

**Comment by maxwellsh** [comment]
Hi Christos,
It looks like your bam file is not indexed hence this error from samtools in the first step
> [main_samview] random alignment retrieval only works for indexed BAM or CRAM files.

Can you index the BAM with samtools index and retry?

Best,
Max

**Comment by proukakis** [comment]
Oh what a muppet I am ! Thanks... and I could have sworn I had indexed it...

however, it still stops at this point:

6.p arm
6.q arm
7.p arm
7.q arm
8.p arm
8.q arm
9.p arm
9.q arm
/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py:324: FutureWarning:

from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.

PaSDqc/psd/38_24.hg19mod.bwa.sorted.chroms.spec
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/bin/PaSDqc", line 102, in _build_and_save
    psd = PaSDqc.PSDTools.SamplePSD.build_from_dir(str(dir_in), sample=sample, clean=clean, build=build)
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 268, in build_from_dir
    df = cls._build_dataframe(file_list, build)
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 313, in _build_dataframe
    psd_list = [ChromPSD(str(f)) for f in f_list]
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 313, in <listcomp>
    psd_list = [ChromPSD(str(f)) for f in f_list]
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 35, in __init__
    self.chrom = str(self.df.chrom.iloc[0])
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/usr/local/bin/PaSDqc", line 210, in QC
    PSD(args)
  File "/usr/local/bin/PaSDqc", line 95, in PSD
    [p.get() for p in res]
  File "/usr/local/bin/PaSDqc", line 95, in <listcomp>
    [p.get() for p in res]
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: single positional indexer is out-of-bounds


any idea?

i will try to run other files, and the one from SRA, later

christos

**Comment by proukakis** [comment]
i was unable to get it work, although the example was running

.p arm
9.q arm
/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py:324: FutureWarning:

from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.

PaSDqc/psd/38_24.hg19mod.bwa.sorted.chroms.spec
PaSDqc/psd/38_24.hg19mod.bwa.chroms.spec
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/bin/PaSDqc", line 102, in _build_and_save
    psd = PaSDqc.PSDTools.SamplePSD.build_from_dir(str(dir_in), sample=sample, clean=clean, build=build)
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 268, in build_from_dir
    df = cls._build_dataframe(file_list, build)
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 313, in _build_dataframe
    psd_list = [ChromPSD(str(f)) for f in f_list]
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 313, in <listcomp>
    psd_list = [ChromPSD(str(f)) for f in f_list]
  File "/usr/local/lib/python3.6/site-packages/PaSDqc/PSDTools.py", line 35, in __init__
    self.chrom = str(self.df.chrom.iloc[0])
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1500, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2230, in _getitem_axis
    self._validate_integer(key, axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 2139, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/usr/local/bin/PaSDqc", line 210, in QC
    PSD(args)
  File "/usr/local/bin/PaSDqc", line 95, in PSD
    [p.get() for p in res]
  File "/usr/local/bin/PaSDqc", line 95, in <listcomp>
    [p.get() for p in res]
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
IndexError: single positional indexer is out-of-bounds


i then cleaned up my brew, upgraded to python 3.7 ,and installed all dependencies

then tried to build, and failed

make
python setup.py sdist
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "setup.py", line 56, in <module>
    install_requires = check_dependencies()
  File "setup.py", line 24, in check_dependencies
    import matplotlib
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 351
    print(s, file=self.fileo)
                 ^
SyntaxError: invalid syntax
make: *** [dist] Error 1

I will try to get local help, but is it possible that it cant compile on python 3.7? (sorry if this is a stupid question)

**Comment by maxwellsh** [comment]
Hmm, the make error seems like something is wrong with the python setup.

Just to confirm, you were not able to get the software to run on the SRA bam?

**Comment by proukakis** [comment]
Yes  it does, thanks

So I had a problem with the SRA bam- the numbers in the paper seemed to refer to experiment rather than a single bam file in SRA- or i misunderstood something

And I downloaded one which gave me an error that suggested that the reference didn’t match- as if it came from a ref with “chr” included, if I understood correctly

I am away this week but someone is working on it on a different mac which will hopefully work, and I will try if needed via anaconda next week, and get back to you and / or close thread if all fine, thanks again

**Comment by maxwellsh** [comment]
Ah, I am sorry about the SRA problems. I wasn't involved in uploading them, so I am afraid I don't know much about those files.

As for the outstanding chr9 issue, my guess is that your bam file has little (or no) coverage on chr9; this would produce the error you've encountered as the program would try to index an empty array. This is an easy thing to check once you've got the python environment set up again. I've meant to correct this behavior for sometime (it would be far better for PaSDqc to print a warning and skip the chromosome rather than fail outright). I could integrate this feature if you'd be willing to test for me =).

**Comment by mariakalyva** [comment]
Hello Max,

I am working with Christos.
So I was able to run your pipeline and create the chrom.spec files but I got this error afterwards. If you have any idea what might have caused it, that would be extremely helpful.

My command: `PaSDqc QC -d/Users/maria/Desktop/Diego_P7006-124586463/Fastq/pons/bams -o /Users/maria/Desktop/PaSD-qc -c categorical_spectra_0.1x.txt`

The warning:

`Reading data from /Users/maria/Desktop/PaSD-qc
/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc:117: FutureWarning:

read_table is deprecated, use read_csv instead, passing sep='\t'.

Fitting chromosome and sample curves
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/series.py:4141: FutureWarning:

from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/extra_tools.py:54: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 211, in QC
    report(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 123, in report
    [psd.fit_chrom_curves(chroms, bulk=args.bulk) for psd in psd_list]
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 123, in <listcomp>
    [psd.fit_chrom_curves(chroms, bulk=args.bulk) for psd in psd_list]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/PSDTools.py", line 376, in fit_chrom_curves
    amp_chrom.fit_curve(method=method, bulk=bulk)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/amplicon.py", line 197, in fit_curve
    popt, pcov = scipy.optimize.curve_fit(f_fit, period, psd_cut, method='trf')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 703, in curve_fit
    ydata = np.asarray_chkfinite(ydata)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs'
Christoss-giant-Mac:bams maria$ 
`

**Comment by mariakalyva** [comment]
Hello Max,

I am working with Christos.
So I was able to run your pipeline and create the chrom.spec files but I got this error afterwards. If you have any idea what might have caused it, that would be extremely helpful.

My command: PaSDqc QC -d/Users/maria/Desktop/Diego_P7006-124586463/Fastq/pons/bams -o /Users/maria/Desktop/PaSD-qc -c db/categorical_spectra_0.1x.txt

The error:
`Reading data from /Users/maria/Desktop/PaSD-qc
/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc:117: FutureWarning:

read_table is deprecated, use read_csv instead, passing sep='\t'.

Fitting chromosome and sample curves
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/series.py:4141: FutureWarning:

from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/extra_tools.py:54: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.

Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 265, in 
args.func(args)
File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 211, in QC
report(args)
File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 123, in report
[psd.fit_chrom_curves(chroms, bulk=args.bulk) for psd in psd_list]
File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 123, in 
[psd.fit_chrom_curves(chroms, bulk=args.bulk) for psd in psd_list]
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/PSDTools.py", line 376, in fit_chrom_curves
amp_chrom.fit_curve(method=method, bulk=bulk)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/amplicon.py", line 197, in fit_curve
popt, pcov = scipy.optimize.curve_fit(f_fit, period, psd_cut, method='trf')
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 703, in curve_fit
ydata = np.asarray_chkfinite(ydata)
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
"array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs`

**Comment by maxwellsh** [comment]
Hi Maria,
Great news that you you've generated the spec files. This is a fairly common error and usually easily fixed. First things first, can you confirm that the chrom.spec files are not empty?

**Comment by mariakalyva** [comment]
Happy to hear that. They are not empty and around 3.5 MB each. 

Here is a screenshot of how they look
![image](https://user-images.githubusercontent.com/43231659/55170458-828c5c80-516e-11e9-8edd-a7256c043f6e.png)

**Comment by maxwellsh** [comment]
Great! How many samples are you profiling? My guess is that you have one or two samples of very bad quality (lots of regions of very low or no coverage). The estimation procedure will fail in such cases. Can you try generating a report using some small subsets of the chrom.spec files?

You can just copy a few to a new directory and run
```PaSDqc report -d <directory> -c db/categorical_spectra_0.1x.txt ```

**Comment by mariakalyva** [comment]
I tried but I got this error.

`PaSDqc report -d /Users/maria/Desktop/example -c db/categorical_spectra_0.1x.txt
Reading data from /Users/maria/Desktop/example
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 119, in report
    freq = psd_list[0].freq
IndexError: list index out of range`

I tried 3 samples just for testing before. I will try again now with more samples and higher reads.

**Comment by maxwellsh** [comment]
How many files did you copy to `examples`? That error implies the program did not find any chrom.spec files to read

**Comment by mariakalyva** [comment]
So sorry I forgot to create a psd directory inside the example directory I moved the files.
So now it worked and produced the same error for these 3 spec files created from the 3 test files I also used before.


`eduroam-int-dhcp-97-153-178:PaSDqc maria$ PaSDqc report -d /Users/maria/PaSDqc/examples/ -c db/categorical_spectra_0.1x.txt
01_example_report/                     06_example_clustering/
02_example-basic_PSD/                  07_example_region_blacklist/
03_example-amplicon_distribution/      08_example_make_gold_standard_spectra/
04_example-dispersion_estimation/      data/
05_example_chromosome_classification/  
eduroam-int-dhcp-97-153-178:PaSDqc maria$ PaSDqc report -d /Users/maria/PaSDqc/examples/01_example_report/ -c db/categorical_spectra_0.1x.txt
PaSDqc_report.html  data/               psd/                
eduroam-int-dhcp-97-153-178:PaSDqc maria$ PaSDqc report -d /Users/maria/Desktop/example/ -c db/categorical_spectra_0.1x.txt
Reading data from /Users/maria/Desktop/example
/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc:117: FutureWarning:

read_table is deprecated, use read_csv instead, passing sep='\t'.

Fitting chromosome and sample curves
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pandas/core/series.py:4141: FutureWarning:

from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/extra_tools.py:54: FutureWarning:

Method .as_matrix will be removed in a future version. Use .values instead.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 265, in <module>
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 123, in report
    [psd.fit_chrom_curves(chroms, bulk=args.bulk) for psd in psd_list]
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/PaSDqc", line 123, in <listcomp>
    [psd.fit_chrom_curves(chroms, bulk=args.bulk) for psd in psd_list]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/PSDTools.py", line 376, in fit_chrom_curves
    amp_chrom.fit_curve(method=method, bulk=bulk)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PaSDqc/amplicon.py", line 197, in fit_curve
    popt, pcov = scipy.optimize.curve_fit(f_fit, period, psd_cut, method='trf')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/scipy/optimize/minpack.py", line 703, in curve_fit
    ydata = np.asarray_chkfinite(ydata)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/function_base.py", line 498, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs`


I will try to run the pipeline again with more files and more reads now

**Comment by maxwellsh** [comment]
That's a good next step. I would suggest a minimum coverage of 0.5x per bam. Coverage >1X is optimal for performance, though.

**Comment by mariakalyva** [comment]
I see! Thank you very for the help.

Maria

**Comment by proukakis** [comment]
Hello- a very brief note- we are citing this in a book chapter, and i will say that optimal coverage is >1, based on the above- hopes that's ok, christos

**Comment by maxwellsh** [comment]
Hi Christos, yes that is accurate. Many thanks for checking.
